name: vonum
description: Learn flutter code
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  common:
    path: package/common
  source:
    path: package/source
  theme:
    path: package/theme
  widget:
    path: package/widget

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true